ci: build binaries and generate man page
storj/storagenode-deb pull request #13
Opened 2020-10-13 10:44 UTC by Fadila82

2020-11-03 13:57 UTC, rikysya commented
note: Jenkins failed to build

2020-11-04 12:39 UTC, ifraixedes requested changes

2020-11-04 12:39 UTC, ifraixedes commented on docker/Dockerfile.binaries
> +RUN ls /usr/share/nginx/html
do we need this command for anything?

2020-11-04 12:39 UTC, ifraixedes commented on packaging/debian/storagenode.config
> +	    ;;
replace tab by spaces.
There are a few more down in this file.

2020-11-04 12:39 UTC, ifraixedes commented on packaging/debian/storagenode.config
> +	      if [[ ! "$diskspace" =~ ^[0-9]+[GTgt]{1} ]]; then
In the regular expression, it's better to remove `{1}` because it's implicit and add `$` at the end to filter out wrong formats like `100G,3`, etc.

2020-11-04 12:39 UTC, ifraixedes commented on packaging/debian/storagenode.config
> +		  if [ "$ERR_STATE" != "$ERR_BACK" ]; then
I see that this is used across this file but shouldn't be better to use `if [ "$ERR_STATE" == "$ERR_CONTINUE" ]`

2020-12-28 21:42 UTC, closed without merging